language: java
jdk:
- oraclejdk7
- openjdk7
before_install:
- openssl aes-256-cbc -K $encrypted_970bc05c31a6_key -iv $encrypted_970bc05c31a6_iv
  -in travisci_rsa.enc -out travisci_rsa -d
- chmod 0600 travisci_rsa
- cp travisci_rsa ~/.ssh/id_rsa
install:
- sudo apt-get update -qq
- sudo apt-get install -qq doxygen graphviz
after_script:
- ./doxygen-deploy.sh
