/*
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * NewGameWindow.java
 *
 * Created on 2009-10-20, 15:11:49
 */
package jchess.gui;

import jchess.util.StringResources;

import javax.swing.*;

/**
 * @author donmateo
 */
class NewGameWindow extends JDialog {

    /**
     * Creates new form NewGameWindow
     */
    public NewGameWindow(GUI parent) {
        super(parent);
        initComponents();

        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setTitle(StringResources.GUI.getString("newGameWindow.title"));

        add(new DrawLocalSettings(this));

        pack();
    }

    public void createNewGame(String firstName,
                              String secondName,
                              String thirdName) {
        ((GUI) getParent()).createNewGame(firstName,
                                          secondName,
                                          thirdName);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewGameWindow(null).setVisible(true);
            }
        });
    }


}
